# Generated by Django 3.0.8 on 2020-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qaplatform', '0004_auto_20200802_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default=0, max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=280),
        ),
    ]
