# Generated by Django 3.0.8 on 2020-08-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaplatform', '0005_auto_20200807_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_data',
            new_name='comment_date',
        ),
    ]
