# Generated by Django 3.2 on 2021-08-17 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qaplatform', '0008_auto_20201014_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 17, 16, 31, 551351, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 17, 16, 31, 551844, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 17, 16, 31, 550756, tzinfo=utc), verbose_name='date published'),
        ),
    ]
