# Generated by Django 3.1 on 2020-10-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaplatform', '0008_auto_20201011_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvote',
        ),
    ]
