# Generated by Django 3.1 on 2020-10-11 18:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qaplatform', '0009_auto_20201011_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='new_downvote',
            new_name='downvote',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='new_upvote',
            new_name='upvote',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='new_downvote',
            new_name='downvote',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='new_upvote',
            new_name='upvote',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='new_downvote',
            new_name='downvote',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='new_upvote',
            new_name='upvote',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('upvote', 'downvote')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('upvote', 'downvote')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('upvote', 'downvote')},
        ),
    ]
