# Generated by Django 3.1 on 2020-10-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaplatform', '0010_auto_20201011_1835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvote',
        ),
    ]
