# Generated by Django 3.1 on 2020-10-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaauth', '0002_auto_20200917_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
