# Generated by Django 3.1 on 2020-10-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaauth', '0003_auto_20201005_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='qaauth.profile')),
                ('profile_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='qaauth.profile')),
            ],
            options={
                'unique_together': {('profile', 'profile_following')},
            },
        ),
        migrations.RemoveField(
            model_name='following',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
