# Generated by Django 3.2 on 2021-08-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaauth', '0004_auto_20201005_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='qaauth.profile'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='profile_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='qaauth.profile'),
        ),
    ]
